# Generated by Django 2.1.5 on 2019-01-08 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=255, unique=True)),
                ('elasticname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('messageid', models.CharField(max_length=255)),
                ('channelid', models.CharField(max_length=255)),
                ('serverid', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Snip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeposted', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField()),
                ('content_html', models.TextField(default='')),
                ('isdeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SnipAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discordid', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='snip',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snips.SnipAuthor'),
        ),
        migrations.AddField(
            model_name='snip',
            name='tags',
            field=models.ManyToManyField(to='snips.CharacterTag'),
        ),
        migrations.AddField(
            model_name='discordmessage',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snips.Snip'),
        ),
    ]
